# Docker compose to have Zookeeper, Kafka, and Kafka Manager running for development.
# Provided by @chris-zen

kafka-manager:
  image: vescel/kafka-manager
  ports:
    - "9000:9000"
  env_file: _env
  environment:
    APPLICATION_SECRET: letmein
